'@novu/api-service':
  - apps/api/**/*
'@novu/worker':
  - apps/worker/**/*
'@novu/web':
  - apps/web/**/*
'@novu/dashboard':
  - apps/dashboard/**/*
'@novu/ws':
  - apps/ws/**/*
'@novu/inbound-mail':
  - apps/inbound-mail/**/*
'@novu/webhook':
  - apps/webhook/**/*
'@novu/dal':
  - libs/dal/**/*
'@novu/shared':
  - packages/shared/**/*
'providers':
  - providers/**/*
'CI/CD':
  - .github/**/*
'docker':
  - docker/**/*
'scripts':
  - scripts/**/*
